// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import ()

type BrakeManager struct {
	ID                                                 int64 `json:"id"`
	State                                              int64 `json:"state"`
	HydrolicPressureLoss                               int64 `json:"hydrolic_pressure_loss"`
	CriticalPodAccelerationMesureTimeout               int64 `json:"critical_pod_acceleration_mesure_timeout"`
	CriticalPodDecelerationInstructionTimeout          int64 `json:"critical_pod_deceleration_instruction_timeout"`
	VerinBlocked                                       int64 `json:"verin_blocked"`
	EmergencyValveOpenWithoutHydrolicPressorDiminution int64 `json:"emergency_valve_open_without_hydrolic_pressor_diminution"`
	CriticalEmergencyBrakesWithoutDeceleration         int64 `json:"critical_emergency_brakes_without_deceleration"`
	MesuredDistanceLessThanDesired                     int64 `json:"mesured_distance_less_than_desired"`
	MesuredDistanceGreaterAsDesired                    int64 `json:"mesured_distance_greater_as_desired"`
}

type MainComputer struct {
	ID    int64 `json:"id"`
	State int64 `json:"state"`
}
